### ISSUE TITLE
最新版导致vite一直挂起

### ISSUE THREAD

**Issue by WangChong99** [vite-plugin/vite-plugin-lang-jsx#3]
插件用最新版1.4.1就会导致vite启动后一直进不去页面,document加载一直处于挂起状态,浏览器控制台无任何报错,什么打印都没有
就像这样
![微信图片_20220801094823](https://user-images.githubusercontent.com/74531242/182057119-75b479f4-1f4b-41a7-b736-998edf0e9643.jpg)
我换成以前的版本1.3.3就正常启动了

我是在vue-element-admin的基础上配置的
方法如下

注意 使用了jsx语法的vue文件需要在<script>加上lang="jsx"
package.json

"scripts": {
 "vite": "vite"
},
"dependencies": {
  "@vue/composition-api": "1.6.2"
},
​
"devDependencies": {
"@originjs/vite-plugin-commonjs": "1.0.3",
"@originjs/vite-plugin-require-context": "1.0.9",
"unplugin-vue2-script-setup": "0.11.0",
"vite": "2.9.9",
"vite-plugin-html-template": "1.1.4",
"vite-plugin-lang-jsx": "1.3.3",
"vite-plugin-vue2": "2.0.1",
},

main.js

import VueCompositionAPI from '@vue/composition-api'
Vue.use(VueCompositionAPI)

vite.config.js

import {defineConfig} from 'vite'
import {createVuePlugin} from 'vite-plugin-vue2'
import {viteCommonjs} from "@originjs/vite-plugin-commonjs"
import langJsx from 'vite-plugin-lang-jsx';
import ScriptSetup from 'unplugin-vue2-script-setup/vite'
import htmlTemplate from 'vite-plugin-html-template'
import ViteRequireContext from '@originjs/vite-plugin-require-context'
import {join} from 'path'

export default defineConfig({
  define: {
    'process.env': process.env
  },
  plugins: [
    createVuePlugin({
      jsx: true,
      jsxOptions: { //配置jsx
        compositionAPI: true
      }
    }),
    langJsx(), //启用jsx
    viteCommonjs({ //require引入转换成import引入
      skipPreBuild: true
    }),
    ScriptSetup({ /* options */}), //使用<script-setup>
    htmlTemplate({ //vite 默认使用根目录下的 index.html,将路径改到public目录下
      pages: {
        index: {
          template: './public/index.html'
        }
      }
    }),
    ViteRequireContext()  //Support require.context in vite.
  ],
  resolve: {
    extensions: ['.vue', '.mjs', '.js', '.ts', '.jsx', '.tsx', '.json'],
    alias: [
      // 适配 @xxxx、@/xxxx
      {find: '@', replacement: join(__dirname, 'src')},
      {find: '~@', replacement: join(__dirname, 'src')}
    ]
  },
  css: {
    preprocessorOptions: {
      scss: { //配置全局scss文件
        sourceMap: false,
        additionalData(source, fp) {
          // All scss files ending with index.scss
          // will not re-import additionalData
          if (fp.endsWith('index.scss')) return source;
          // Use additionalData from legacy nuxt scss options
          return `@import "@/styles/index.scss"; ${source}`
        }
      }
    }
  },
  server: {
    host: true,
    port: 9534,
    open: false, //启动后不自动打开
    proxy: {

    }
  },
})

**Comment by caoxiemeihao** [comment]
Thanks for your feedback!
I will try fix the BUG 🐞

**Comment by WangChong99** [comment]
上面发的那个vite.config.js文件里 我之前不小心把 langJsx() 写在了createVuePlugin 后面 , 但是我改写到前面后,最新版依然会挂起,好像与这个顺序关系不大

**Comment by caoxiemeihao** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/26263658/182368462-4b282386-f943-4cff-9916-271a47e855cf.png">

Now, `vite-plugin-lang-jsx` [![NPM version](https://img.shields.io/npm/v/vite-plugin-lang-jsx.svg?style=flat)](https://npmjs.org/package/vite-plugin-lang-jsx) is available.
