### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by MongoCZK** [vite-plugin/vite-plugin-lang-jsx#7]
问题： build的时候报错，如
![image](https://user-images.githubusercontent.com/37548625/211219737-1a89af17-2c9c-4c9f-8eee-34f5ee5bfa6e.png)

配置：
vite: 3.2.5
vite-plugin-lang-jsx: 1.4.2
vite-plugin-vue2:  2.0.3

**Comment by caoxiemeihao** [comment]
可否提供一下最小化复现的 Demo?

**Comment by i-ce-fish** [comment]
一模一样

**Comment by yejimeiming** [comment]
> 一模一样

可以在 `node_modules` 中这里加个判断试试，如果可以的话欢迎提个 PR
https://github.com/vite-plugin/vite-plugin-lang-jsx/blob/v1.5.2/index.js#L44

`v1.4.2` 版本中报错在 39 行
https://github.com/vite-plugin/vite-plugin-lang-jsx/blob/v1.4.2/index.js#L39
